### ISSUE TITLE
astroquery.mast returning unexpected results with mtFlag

### ISSUE THREAD

**Issue by nedervold** [astropy/astroquery#1042]
When I call `Observations.query_criteria(proposal_id="5167", mtFlag=True)` I get no responses.

When I call `Observations.query_criteria(proposal_id="5167", mtFlag=False)` I get no responses.

When I call `Observations.query_criteria(proposal_id="5167")` I get 45 rows, all of whose mtFlag values seem to be `False`.

When I use the HST Search form at [http://archive.stsci.edu/hst/search.php](url), setting "Proposal ID" to "5167" and "User-specified field 1: MT Flag" to "T", I get 28 rows.

One file in both sets of results, U2NO0401T_DRZ.FITS, is an image of Jupiter, so I'd expect it to have mtFlag=True.

I'm working with Dr. Mark Showalter at the Seti Institute: we need to be able to query for moving-target files in MAST that have changed since a given date.  This anomaly makes that difficult.

It's possible that this is purely a MAST API issue, not an astroquery.mast issue.  I'm sending archive@stsci.edu a copy of this too.

**Comment by keflavich** [comment]
Thanks.  It might be that you should use `mtFlag='T'` or `mtflag='F'`, based on your problem description.  If that turns out to be the case, we can add a tool in astroquery to map the python `True/False` objects to `'T'/'F'`

**Comment by nedervold** [comment]
Nope: just tried 'T'/'F' with the same results.  'True' and 'False' as strings instead of booleans don't work either.  As I said, I've asked archive@stsci.edu to look into this too, so if you see nothing obvious, maybe they will have a solution.  Thanks for your near instantaneous reply.

**Comment by keflavich** [comment]
Alright, let's wait to hear back from them.  You can refer them to this Issue; they may be able to contribute directly.

**Comment by ceb8** [comment]
@nedervold There are a couple of different things going on here.  

The reason you see 45 results that appear to have mtFlag set to False when you omit that criteria altogether is that the mtFlag is not in fact set at all for those observations. If you are using an older version of astroquery these probably show up as False (default in a boolean column), however if you update to a newer version you should see that the mtFlag values are actually masked out, meaning that the flag has not been set.

This search is not actually equivalent to the HST search you sent, but rather is equivalent to [this Discovery Portal search](https://mast.stsci.edu/portal/Mashup/Clients/Mast/Portal.html?searchQuery=%7B%22service%22%3A%22CAOMFILTERED%22%2C%22inputText%22%3A%5B%7B%22paramName%22%3A%22proposal_id%22%2C%22niceName%22%3A%22proposal_id%22%2C%22values%22%3A%5B%5D%2C%22valString%22%3A%225167%22%2C%22isDate%22%3Afalse%2C%22freeText%22%3A%225167%22%2C%22displayString%22%3A%225167%22%7D%5D%2C%22position%22%3A%22undefined%2C%20undefined%2C%20undefined%22%2C%22paramsService%22%3A%22Mast.Caom.Filtered%22%2C%22title%22%3A%22MAST%3A%20%20Advanced%20Search%201%22%2C%22tooltip%22%3A%225167%3B%20%22%2C%22columns%22%3A%22*%22%7D).   (Note that in this case the mtFlag shows up as false rather than unset, this is a known bug where not-set is rendered as false.) I don't know why the output of this search differs from the one you did using the HST form, but I'll check into it.

**Comment by ceb8** [comment]
@nedervold There was a problem with database ingest that has been corrected, if you rerun your search now, the mtFlag should show as True.  Thanks for bringing this to our attention.

**Comment by nedervold** [comment]
So now what I'm seeing is:

Observations.query_criteria(proposal_id="5167", mtFlag=True) => no responses.
When I call Observations.query_criteria(proposal_id="5167", mtFlag=False) => no responses.
When I call Observations.query_criteria(proposal_id="5167") => 45 rows, all of whose mtFlag is True.

Are these results expected?  I'd expect the first call to return 45 rows.

**Comment by ceb8** [comment]
@nedervold  I get 45 rows when I do 
`Observations.query_criteria(proposal_id="5167", mtFlag=True)`
so, I am not sure what is different about your call that you are seeing something different. Is that a verbatim copy of what you ran?

**Comment by nedervold** [comment]
Oops—user error.  Sorry for wasting your time.

I'd left the code using 'T' and 'F' per the second comment on this issue.  The code now works fine with either the boolean `True` or the string `'True'`.

Thanks for all your help.

**Comment by ceb8** [comment]
@nedervold Whew!  Glad it is not something weird and unreproducible!  Yeah it has to be either the boolean or string true/false because that is what the serializer knows how to translate into a boolean for the database.

**Comment by pllim** [comment]
If this is no longer an issue, please close it. Thanks!

**Comment by nedervold** [comment]
Issue fixed.  Thank you, all.  Closing…
