### ISSUE TITLE
How to generate a random set of data from SIMBAD without pulling a huge amount of objects?

### ISSUE THREAD

**Issue by LJNolan** [astropy/astroquery#1100]
Hello everyone, first of all I'm very sorry if this is the wrong place to put this sort of help request, I don't use GitHub very often and am unfamiliar with how organization works.  My issue is as follows.  

  For a project I'm working on, suffice to say that I need a set of certain magnitude data and IDs in a table, which I split into a numpy array and list, respectively.  The data is pulled from SIMBAD via queries of a few specific object types which contain very few objects (no worries of timeout), and then a randomized list of about 60 objects without those object types to ensure statistical validity.  Currently, I generate this set of data by indexing all of SIMBAD for objects without the object type I'm looking at that also have the requisite magnitude data available, which all told still leaves about 65,000 objects.  

  To avoid a timeout error, I set the ROW_LIMIT on my Simbad object to 300, as I timeout with anything higher, and select a random index from 0 to 240 from which to select the 60 following objects as my "random" data set.  Unfortunately, due to how the data in SIMBAD is organized, this results in my "random" set typically consisting entirely of one type of object, which poses serious problems for my research.  So, this leads to my question:  Is it possible to get a completely random set of ~60 objects and their data from SIMBAD of the 65,000 objects that have the criteria I set?  For example, if I ran the code I would get data from objects 31,762; 205; 60,007; 24,593 etc.  Any help or advice would be greatly appreciated.

**Comment by keflavich** [comment]
You should be able to just change the timeout: `Simbad.TIMEOUT = 300`, for example.

That said, I'm not sure it is ever possible to get a 'random' result from a SIMBAD query.  I certainly hope all queries are deterministic.  Perhaps what you mean to do is obtain all 65k objects and then use a random selection tool to select from among them?

**Comment by LJNolan** [comment]
Well, thank you very much for the information about the timeout, I had no idea.  I was originally thinking that obtaining all the objects would be impossible because of a timeout and/or reasonable time/bandwidth constraints, but it occurred to me that it might work to obtain object IDs for all the objects, take a random selection of those, then query SIMBAD individually for those objects, so that I don't need to query all of the data for all of the objects.  Would this sound feasible?

**Comment by aoberto** [comment]
Hi

you can not add an other criteria based on region using random 
coordinates you generate ?

**Comment by LJNolan** [comment]
Sorry if I'm misunderstanding aoberto, are you saying to add another criterion to my search based on a random physical location in the sky (i.e. coordinates)?  Unfortunately, my criteria-based query already has 5 criteria, though it might be possible to set up an additional query for location, my program just isn't set up to generate coordinates.  I will look into it however, assuming I'm understanding you correctly.

**Comment by ManonMarchand** [comment]
Hi, 

If you want a single sample, you could get it with a TAP request on simbad. 

```python
import pyvo
# sets TAP to talk with Simbad
simbadtap = pyvo.dal.TAPService("https://simbad.u-strasbg.fr/simbad/sim-tap")
# define the query
query = """
select top 10 oid, B, rand(1.0) as my_rand from basic 
join allfluxes on oid = oidref
where (otype = 'BS*') and B is not null
ORDER BY my_rand
"""
result = simbadtap.search(query)
```

that should give you 10 random blue straggler stars that have a measurement for the B flux. 

```
  oid   |  B   |       my_rand       |otype
--------|------|---------------------|-----
3280307 |15.9  |0.0020104674622416496|"BS*"
7759495 |11.65 |0.0027135503478348255|"BS*"
303265  |15.371|0.004091036505997181 |"BS*"
5547357 |23.08 |0.004872792866080999 |"BS*"
11486085|23.19 |0.005682441871613264 |"BS*"
5653363 |19.77 |0.006025818642228842 |"BS*"
5348741 |16.813|0.006197358947247267 |"BS*"
5563922 |17.6  |0.007107251323759556 |"BS*"
5565496 |15.61 |0.0072091249749064445|"BS*"
1012959 |8.19  |0.007258302066475153 |"BS*"
```

### Explanations

The way it works is that the TAP query is a direct access to all [Simbad relational database](https://simbad.cds.unistra.fr/simbad/tap/tapsearch.html). You have access to all its sub-tables that can be joined together afterwards. Here we join `basic` that contains the `otype` information with `allfluxes` that contains the magnitudes. This allows for the criteria on otype and B. Then, a random column is generated with `rand`. Careful, here 1.0 is the seed so change that to have a different sample. Then, ordering by the random column and selecting the ten first ones will get you a random sample. 

### Note: 

This is a quite heavy query for simbad servers since the order by is made on a non-indexed column. 
Getting the 65 000 rows once and working with them locally might be better depending on the number of times you run the sample query. 

Hope this answers the question? I'll close the issue for now but don't hesitate to come back if needed.
