### ISSUE TITLE
Interested in contributing as either a GSoC 2019 project idea or volunteer work

### ISSUE THREAD

**Issue by kakirastern** [astropy/astroquery#1378]
Hi, I am interested in contributing to Astropy's astroquery as either a GSoC 2019 project idea, or as regular volunteer work. I have been looking at the project descriptions at [https://openastronomy.org/gsoc/gsoc2019/#/projects?project=add_additional_archives_to_astroquery](https://openastronomy.org/gsoc/gsoc2019/#/projects?project=add_additional_archives_to_astroquery), and found the task of adding new modules to **_astronomical archives which are currently lacking astroquery modules_** particularly enticing. Presently, I would like to know if there are any other details not listed in the link above that I should be aware of before I start to contribute via PR's. Any other suggestion(s) such as tips on workflow, some potential gotcha's, etc. would be much appreciated too.

**Comment by bsipocz** [comment]
Hey,

I'm going to close this issue here, and let's take the discussion to slack instead. As a brief summary: the workflow is the same as for astropy. This GSoC project is kept very generic as this is actually a project that allows the most flexibility on the student side, there are way too much work to be done here, so can pick and choose what interest you most.

**Comment by kakirastern** [comment]
Sure @bsipocz
