### ISSUE TITLE
astroquery.gaia Some table columns contain 'bytes' objects, and cannot be used as selection. Also causing 'Job object has no attribute set_failed', 

### ISSUE THREAD

**Issue by mar-ses** [astropy/astroquery#1434]
Hello,

I've been having a problem where I try to find stars in the Gaia catalogue, knowing their 2MASS names, which are in RA-DEC format, i.e: 15341356-6000106. In `gaiadr2.tmass_best_neighbour`, these are under the column `original_ext_source_id`

So I try to crossreference between `gaiadr2.tmass_best_neighbour` and `gaiadr2.gaia_source`. However I'm getting an odd error. The following code is a test that attempts to reproduce it by taking a random 'original_ext_source_id` and attempting to recover it:

```
job = Gaia.launch_job("SELECT TOP 1 original_ext_source_id FROM gaiadr2.tmass_best_neighbour "
                      "WHERE tmass_oid IS NOT NULL")
r = job.get_results()
tmass_ext_id_test = r['original_ext_source_id'][0]

command = ("SELECT * FROM gaiadr2.tmass_best_neighbour AS tbest "
           "WHERE tbest.original_ext_source_id = {}".format(str(tmass_ext_id_test)))
job = Gaia.launch_job(command)      # FAILS ON THIS COMMAND
r = job.get_results()
```

First of all, the exception thrown is a `AttributeError: 'Job' object has no attribute 'set_failed'` which appears to be related to a separate issue in `astroquery` or `astropy.tap` or whatever.

However, I don't see a reason why the above code should produce any error. It takes a `original_ext_source_id` in a table, and tries to find it in the same table. I'm a compelte novice in SQL or ADQL, so I'm not sure how to debug this, but here is where I believe an issue may possibly lie (though I'm not sure):

```
print(r['original_ext_source_id'][0])
b'15341356-6000106'
```
Unlike other columns, `original_ext_source_id` seems to store or return a bytes object. I don't know why exactly, does that mean the entries in the actual tables are stored as bytes objects? In any cases, could that possibly causing issues with the comparison when I'm trying to run the command:

`SELECT * FROM gaiadr2.tmass_best_neighbour AS tbest WHERE tbest.original_ext_source_id = b'15341356-6000106'`

I tried to turn the bytes object into a normal str (unicode in python) with:

`tmass_ext_id_test = r['original_ext_source_id'][0].decode("utf-8")`

But this still produces an error; perhaps SQL is still having trouble comparing the unicode string with the stored bytes objects? In any case, does anyone know how this can be solved?

**Comment by smoh** [comment]
- The `AttributeError` indeed must be related to an internal bug unrelated.

- You must have gotten an `HTTPError` with error code 500 without any message. The problem with the modified query (where bytes were appropriately converted to a string) is that the string value you want to compare a column to needs to be inside single quotes as in `'abcde'`:
```sql
SELECT * FROM gaiadr2.tmass_best_neighbour AS tbest
WHERE tbest.original_ext_source_id = '15341356-6000106'
```
whereas the current query is
```sql
SELECT * FROM gaiadr2.tmass_best_neighbour AS tbest
WHERE tbest.original_ext_source_id = 15341356-6000106
```

So the only part that needs to be changed is:
```
"WHERE tbest.original_ext_source_id = '{}'"
```

Worth noting that string values in sql must be in single quotes not double quotes as the latter actually means column names.

- This is a shortcoming in the current GaiaTap implementation in astroquery, but the GaiaArchive itself does put out a useful error message and this is contained within the http response. The message from web interface is:

(TAP) Cannot execute query 'SELECT tbest."source_id" AS "source_id",tbest."original_ext_source_id" AS "original_ext_source_id",tbest."angular_distance" AS "angular_distance",tbest."gaia_astrometric_params" AS "gaia_astrometric_params",tbest."tmass_oid" AS "tmass_oid",tbest."number_of_neighbours" AS "number_of_neighbours",tbest."number_of_mates" AS "number_of_mates",tbest."best_neighbour_multiplicity" AS "best_neighbour_multiplicity" FROM gaiadr2.tmass_best_neighbour AS tbest WHERE tbest."original_ext_source_id" = 15341356 - 6000106 Limit 3000000' for job ' (source query: 'SELECT * FROM gaiadr2.tmass_best_neighbour AS tbest WHERE tbest.original_ext_source_id = 15341356-6000106 ')1556757828065O': Can not execute the following SQL: SELECT tbest."source_id" AS "source_id",tbest."original_ext_source_id" AS "original_ext_source_id",tbest."angular_distance" AS "angular_distance",tbest."gaia_astrometric_params" AS "gaia_astrometric_params",tbest."tmass_oid" AS "tmass_oid",tbest."number_of_neighbours" AS "number_of_neighbours",tbest."number_of_mates" AS "number_of_mates",tbest."best_neighbour_multiplicity" AS "best_neighbour_multiplicity" FROM gaiadr2.tmass_best_neighbour AS tbest WHERE tbest."original_ext_source_id" = 15341356 - 6000106 Limit 3000000 . Because: ERROR: operator does not exist: character varying = integer Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts. Position: 490

which is in fact in the content of the http response as you see [here](https://gist.github.com/smoh/c4fc7f8f6d139617ae2302fe2841f9e2).

The astroquery client may be improved in the near future but something to keep in mind.

**Comment by mar-ses** [comment]
Thank you for the help, I wasn't aware of this sorry. Happy to close this then.
