### ISSUE TITLE
CADC: get_images

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#1445]
CADC can do image cutouts.  We'd like to have a `get_images` interface that can access the cutout services.

cc @andamian

**Comment by keflavich** [comment]
http://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/en/doc/data/ documents how to do cutouts

**Comment by caseyjlaw** [comment]
I'd love to see this for CADC data. I'm particularly interested in the VLASS radio data being managed as part of the CIRADA effort.
We currently use something similar for HEASARC in our project (https://github.com/realfastvla/rf_meta_query/blob/master/rf_meta_query/catalog_utils.py).

**Comment by ellieb** [comment]
Hi @keflavich  :wave:

I'm starting to work on this right now (I'm a co-op student at the CADC), and I just want to run the specs by you to make sure I'm on the right track. So the `get_images` function will have a docstring that looks a little like this:

        """
        A coordinate-based query function

        Parameters
        ----------
        coordinates : str or `astropy.coordinates`.
            Coordinates around which to query and cutout
        radius : str or `astropy.units.Quantity`.
            The radius of the cone search and cutout area
        collection: str, optional
            Name of the CADC collection to query, optional
        get_query_payload : bool, optional
            Just return the dict of HTTP request parameters.

        Returns
        -------
        list : A list of `~astropy.io.fits.HDUList` objects

        """

So similar to the CADC `query_region` function, where it will query around passed in coordinates, but instead of returning a table, returns a list of HDUList objects that are cutout around those coordinates. Does this sound about right? Anything I should change?

**Comment by keflavich** [comment]
Yes, this looks right to me.  I don't see anything that needs to be changed

**Comment by bsipocz** [comment]
#1486 has added this! 🎉
