### ISSUE TITLE
Zero results with Observations.query_criteria - calib_level = 0

### ISSUE THREAD

**Issue by Borlaff** [astropy/astroquery#1609]
Hi all, 

I am unable to retrieve a list of RAW files using Observations.query_criteria. The simplest test I can provide:

```
from astroquery.mast import Observations
obs_table = Observations.query_criteria(dataproduct_type=["image"],
                                        s_ra=[188., 189.], s_dec=[25.,27.], calib_level=0)
print(obs_table)

dataproduct_type calib_level obs_collection obs_id ... intentType obsid objID
---------------- ----------- -------------- ------ ... ---------- ----- -----
```

I am using 0.4.dev0
```
pip show astroquery
Name: astroquery
Version: 0.4.dev0
Summary: Functions and classes to access online astronomical data resources
Home-page: http://astropy.org/astroquery
Author: Adam Ginsburg
```
I am probably missing something here. calib_level = 1 to 3 look reasonable outputs, but calib_level = 0 provide no result at all at any position in the sky. Is there a different procedure for raw files? 

Thanks in advance,
Alejandro Borlaff

**Comment by keflavich** [comment]
@ceb8, could you have a look?

**Comment by ceb8** [comment]
Hi @Borlaff, you are encountering the difference between a "data product" and "observation." When you perform an astroquery criteria search, you are querying "observations" which encompass one or more data products. For observations the calib_level column indicates the highest calibration level for the data products within that observation, so if you do a "get_product_list" query on some of the calib_level=1 observations, you should see RAW data products in the list. 

If you truly want to search for only RAW data products as it sounds like you do, probably astroquery is not the best tool since you have to do both the observation and products list searches to access the specific files in question. Instead I would suggest querying CAOM using VO protocols (https://pyvo.readthedocs.io/en/latest/ is the general purpose Python VO interface).  @theresadower is our VO expert and can help you construct the query you want.
