### ISSUE TITLE
Fix utils functions in the alma module

### ISSUE THREAD

**Issue by andamian** [astropy/astroquery#1794]
`astroquery.alma` has been re-factored to use the new TAP services at ALMA but there was not time or resources available to update the functions in `utils` module so this has become a technical debt.

`test_alma_utils.test_make_finder_chart` should be re-enabled when this is fixed.

**Comment by bsipocz** [comment]
This functionality is a bit of an oddball as it's not exactly something the archive provides, but value-added functionality of astroquery. We don't do that for other modules. Besides there are two major issues with it, too: it adds the dependence on pyregions, which is often not up to date with maintenance. Secondly, this functionality is broken now for almost two years, and not many users complained.

So, I would suggest moving it out to somewhere else. I don't have good solutions for the location, maybe it should only live in a tutorial?

**Comment by keflavich** [comment]
Yeah, I agree, this should be moved out.

Note that we do have some "value-added utilities" for other packages, like splatalogue, but they're more for renaming table columns that have awkward row names.

A tutorial is a good idea.

**Comment by bsipocz** [comment]
> Note that we do have some "value-added utilities" for other packages, like splatalogue, but they're more for renaming table columns that have awkward row names.

Yes, that's fine I think as those are more about improved user experience rather than a totally new,  and separate functionality on top of what the archive offers.
Also, I would be more on board with finding charts if it were working and especially if it were to support more archives, but to do that it's a huge tech burden on us and therefore finding a better place for them would be superb. (They could even be  a separate astroquery-charts, etc).

**Comment by keflavich** [comment]
Totally agree.  That was some pretty fragile code that depended on the pre-Adrian version of the ALMA archive anyway.
