### ISSUE TITLE
ESASKY image

### ISSUE THREAD

**Issue by rhuang-astro** [astropy/astroquery#1916]
Hi,

None of the example code in esasky tutorial related to images works for me. 
https://astroquery.readthedocs.io/en/latest/esasky/esasky.html

For example:
```python
>>> astroquery.version.version
'0.4.2.dev'
>>> result = ESASky.query_object_maps("M51", "all")
TableParseError: Failed to parse ESASky VOTABLE result! The raw response can be found in self.response, and the error in self.table_parse_error.

>>> images = ESASky.get_images("m51", radius="20 arcmin",
...                            missions=['Herschel', 'XMM-EPIC'])
Input XMM-EPIC not available.
>>> images = ESASky.get_images("m51", radius="20 arcmin",
...                            missions=['Herschel'])
ttributeError: 'str' object has no attribute 'decode'

>>> from astropy.coordinates import SkyCoord
>>> c = SkyCoord.from_name('M51')
>>> images = ESASky.get_images(c, radius=20*u.arcmin,
...                            missions=['INTEGRAL'])
TableParseError: Failed to parse ESASky VOTABLE result! The raw response can be found in self.response, and the error in self.table_parse_error.

>>> from astropy.coordinates import SkyCoord
>>> c = SkyCoord.from_name('M51')
>>> images = ESASky.get_images(c, radius=20*u.arcmin,missions=['Chandra'])
KeyError: 'product_url'
```
Does it work for you?

I want to fetch chandra's image.

**Comment by keflavich** [comment]
@imbasimba can you help?

**Comment by imbasimba** [comment]
Hi @rhuang-astro,

Indeed that tutorial is very outdated. Some days ago I did update that tutorial as well as addressing many of the issues you have encountered & it is all coming with this pull request
https://github.com/astropy/astroquery/pull/1909

I'll have to look closer on that VO Table issue though.

Regarding Chandra, this module does not yet support downloading of Chandra images, because Chandra is a little special. But I'm sure I can implement it quite fast for you, so just hang in there :)

For now you can query Chandra like this:
`result = ESASky.query_region_maps("M51", "20 arcmin", missions="Chandra")`
Then extract the image url's for manual download like this:
`result['CHANDRA'][0]['access_url']`

**Comment by rhuang-astro** [comment]
It's great!  The last works for me.
Is the Chandra images that you mentioned here the mosiaced Chandra image in http://sky.esa.int/? 

Thank you for your quick reply!

**Comment by imbasimba** [comment]
We do have one Chandra HiPS available in ESASky, which you can see here:
[Chandra HiPS in ESASky](https://sky.esa.int/?target=266.9076916035187%20-28.799222965912925&hips=Chandra+RGB&fov=180&cooframe=J2000&sci=true&lang=en)

On a side note, that VO table issue was a tiny error on the ESASky backend, so I was able to hotfix it directly. So you should no longer get any TableParseErrors. 
Thanks for letting us know about this issue.

**Comment by rhuang-astro** [comment]
Awesome!

**Comment by imbasimba** [comment]
@rhuang-astro 

I just added proper Chandra image download support. I pushed it [here](https://github.com/astropy/astroquery/pull/1909) and you'll have it as soon as it goes through the astroquery review process. 

Cheers,
Henrik
