### ISSUE TITLE
The NASA Exoplanet Archive is moving to TAP

### ISSUE THREAD

**Issue by lgbouma** [astropy/astroquery#2013]
Hi exoplaneteering astroquery experts ,

Updates have been posted at the exoplanet archive that indicate they are moving to a TAP-based table system. For instance, the recently posted planetary systems tables (`ps` and `pscomppars`) are only accessible through TAP, rather than the API service. See:

https://exoplanetarchive.ipac.caltech.edu/docs/TAP/usingTAP.html
https://exoplanetarchive.ipac.caltech.edu/docs/program_interfaces.html

So these latter tables can be accessed via something like
```
from astroquery.utils.tap.core import TapPlus
tap = TapPlus(url="https://exoplanetarchive.ipac.caltech.edu/TAP/")
j = tap.launch_job(query='select top 10 * from ps')
```

This issue raises the question of what updates `astroquery.nasa_exoplanet_archive` will need due to the TAP vs API service change.  One immediate point that could be made in the documentation (I'd be happy to write something up) would be the point above about accessing the new `ps` table via `TapPlus`.

Thanks for your work developing and maintaining this awesome service!
-Luke

**Comment by rickynilsson** [comment]
Hi @lgbouma and astroquery developer community,

Over the past year, we have been advertising the new Planetary Systems (`ps`) and Planetary Systems Composite Parameters (`pscomppars`) tables; these tables are replacing the `exoplanets` and `exomultpars` tables (`ps`) and the `compositepars` table (`pscomppars`).  As part of the modernization of the Archive, the new tables will be accessed through our new TAP service instead of the old API (see https://exoplanetarchive.ipac.caltech.edu/docs/TAP/usingTAP.html).  We are finalizing our release of these updates on April 22 - but as a consequence, the API access to the old tables will be ended to prevent the use of out-dated and potentially wrong data.  Eventually this will be an IPAC-wide effort, and we plan to produce an `astroquery.ipac` package which includes the Exoplanet Archive, but in the meantime we'd like to update `astroquery.nasa_exoplanet_archive`.  For anyone interested (@dfm, @bsipocz, @bmorris3 and others) in contributing to `astroquery.nasa_exoplanet_archive`, we are hoping to work with you to implement a quick fix to minimize headache for the users, while still making them aware of the changes.

Let us know if you are interested, and if you have ideas about how to approach implementation of necessary changes to the `astroquery.nasa_exoplanet_archive` module.  If helpful, we can set up a meeting to discuss some of the options.

Cheers,

Ricky Nilsson
Applications Developer, Caltech-IPAC/NExScI

**Comment by rickynilsson** [comment]
Just an update on this: we have an astroquery fork with changes that restores functionality to the method calls that broke when Archive 2.0 was released last week. Note that users who are specifically calling the deprecated tables will get errors and are prompted to use the new tables. A pull request will best sent to the main project repo tomorrow or early next week.

**Comment by rickynilsson** [comment]
Hi @bsipocz ! Any idea why the checks were cancelled? It says "GitHub Actions has encountered an internal error when running your job."

**Comment by bsipocz** [comment]
I think this can be now closed with the merging of #2067 

If that's not the case, please update the description to include a todo list, so we can keep track in this issue of what is still missing.

**Comment by rickynilsson** [comment]
I think that should be it, but I'll let @lgbouma have the final say since I just hijacked his issue.

**Comment by lgbouma** [comment]
@rickynilsson all good!  Happy to close, and thanks for your work on #2067 :-)
