### ISSUE TITLE
Feature request: Return Coordinate objects

### ISSUE THREAD

**Issue by hamogu** [astropy/astroquery#2043]
There are many ways to use astroquery, but one thing that comes up in a number of services is that they return coordinates. Most notable might be searches forSIMBAD, Gaia,  2MASS catalogs, etc. but also e.g. an ALMA footprint that has a center coordinate. 
Of course, one can construct astropy coordinates from the output tables, but I think it's such a common thing to do that it would be useful to have a method to do that.
I admit, I don't see an easy way to implement is for all catalogs, since the relevant columns are named differently in every service and every table, sometimes one needs knowledge of the epoch or the coordinate system of the returned values etc. On the other hand, that's exactly why it would be useful to just get back a coordinate object that all the right epoch, etc already set!

**Comment by bsipocz** [comment]
I'm afk so searching the issues is troublesome, but I recall that we have a very old issue for this already. Our at least this came up a few times already. 
The code changes shouldn't be complicated, but a lot of it, and we certainly would need some discussion first of what the best approach would be.

**Comment by hamogu** [comment]
I thought it was an obvious think to ask for an tried to search thought the issues. Since I wasn't quite sure what to search for, I then read ~50 issues that looked as if they might be close by hand. After still not finding it, decided to open a new issue. That does not mean it's not been reported before, but it's certainly not easy to find if there is an open issue for it.

**Comment by keflavich** [comment]
found it!  https://github.com/astropy/astroquery/issues/604

**Comment by keflavich** [comment]
@hamogu perhaps you searched for 'coordinate object', while #604 is indexed only under SkyCoord.  Anyway, I shared Brigitta's recollection.

This is still a good idea, and this actually feels suitable as a student project since, at least for some individual cases (e.g., Vizier), it is a reasonably concrete task.  

There are API/UI questions, though, as raised in the other thread - do we just add an extra SkyCoord column?  Do we require a kwarg?  Probably we don't want to just change the defaults.

**Comment by bsipocz** [comment]
Given we found the other issue and it has substantial discussion already, I'm closing this as a duplicate. Let's continue the discussion on the other issue.
