### ISSUE TITLE
Code examples disappered from rendered docs

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2111]
This may be related to the new pytest directive (I don't think so) or some version issues at RTD. Either case, the builds should have failed and notified us before users run into this...

<img width="1037" alt="Screen Shot 2021-07-12 at 16 13 13" src="https://user-images.githubusercontent.com/6788290/125367016-3314cf00-e32c-11eb-92b1-709f6ee95c44.png">

**Comment by pllim** [comment]
I think the problem is there is no Sphinx directive defined for the new `.. doctest-remote-data::` directive in https://github.com/astropy/pytest-doctestplus/blob/main/pytest_doctestplus/sphinx/doctestplus.py . Hopefully the implementation of `.. doctest-skip::` would be a good example to follow.

So, in a way, astropy/pytest-doctestplus#137 was incomplete. Perhaps instead of testing that PR in `astropy` before merge, we should have also tested it here in `astroquery`.

If a fix cannot be done soon, we might need to revert astropy/pytest-doctestplus#137 and do another bug fix release, and then re-apply it in the future together with the new sphinx directive. 🤔

**Comment by bsipocz** [comment]
We'll, water under the bridge, I certainly should have looked at the rendered docs. But going forward I think we shouldn't revert the release, it's not yet used widely, but fix it and do a quick release with the fix.

**Comment by bsipocz** [comment]
Ohh, this is a really deep rabbit hole, I'm getting into multi layer of deprecations. I suppose astroquery very much in need of a large scale infra upgrade...

**Comment by pllim** [comment]
> in need of a large scale infra upgrade

Please let me know if you need help. 😿

**Comment by bsipocz** [comment]
Oh, I'm all done with patching these around, just didn't open the PRs yet.

**Comment by bsipocz** [comment]
This has been resolved with the new sphinx-astropy and pytest-doctestplus releases.
