### ISSUE TITLE
astropy feature freeze broke CI

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#2194]
It seems like that some last-minute merge into astropy feature freeze (stuff still worked 4 days ago...) has broken our CI 😞

**Comment by astrofrog** [comment]
At a quick glance, I think this might be due to https://github.com/astropy/astropy/pull/11682 - which results in some exceptions being different than before in astropy.coordinates, so some of the exception handling code might need to be updated here? (it looks like this might just be from one function so might not be too hard a fix)

**Comment by astrofrog** [comment]
I think the issue is that the exceptions are now chained instead of combined, but there should be a way to get the original exception in principle - I'll put more info here if I find out how.

**Comment by astrofrog** [comment]
I think instead of ``exc.args[1]`` we need to use ``exc.__context__`` but I need to check

**Comment by bsipocz** [comment]
Thanks for looking into this @astrofrog. It's rather annoying that it was a last minute, failing, coordinates merge that did this, again. I wish the project will reach a maturity at some point and stop doing it in each and every release cycle.
