### ISSUE TITLE
SOFIA archive implementation 

### ISSUE THREAD

**Issue by s-goldman** [astropy/astroquery#2232]
At the moment, it doesn't seem that there is access to [SOFIA](https://irsa.ipac.caltech.edu/Missions/sofia.html) data. The [ISRA](https://astroquery.readthedocs.io/en/latest/ipac/irsa/irsa.html) option also doesn't seem to include the SOFIA archive data in the listed catalogs. 

Is this true, and if so, how hard would it be to add as an option?

Thanks!

**Comment by bsipocz** [comment]
Thanks for raising this issue. I'm currently reworking the IRSA module, and will see how easy it will be to build access to the SOFIA archive on top of that.

**Comment by s-goldman** [comment]
@bsipocz Any update on this? Any way I can help?

**Comment by keflavich** [comment]
@bsipocz Have you made any progress on this?  If not, can you point me to an API description?  I tried to reproduce a basic search query based on the https://irsa.ipac.caltech.edu/applications/sofia interface, but there are some hidden variables that have so far thwarted my efforts; I think there's a javascript script that gets executed in the browser that sets the session ID.

I think roughly a session should look like this:
```python
S = requests.Session()
resp1 = S.get('https://irsa.ipac.caltech.edu/applications/sofia')
resp1.raise_for_status()
resp2 = S.post('https://irsa.ipac.caltech.edu/applications/sofia/CmdSrv/sync', data={'cmd': 'CmdInitApp', 'spaName': '--HydraViewer'})
resp2.raise_for_status()
resp3 = S.post('https://irsa.ipac.caltech.edu/frontpage/CmdSrv/sync',
               data={'cmd': 'CmdGetUserInfo',
                     'backToUrl': 'https://irsa.ipac.caltech.edu/applications/sofia/?__action=layout.showDropDown&'})
resp3.raise_for_status()
resp = S.post('https://irsa.ipac.caltech.edu/applications/sofia/CmdSrv/sync',
              params={'cmd': 'tableSearch'},
              data={'request':
                    {"startIdx":0,"pageSize":100,#"ffSessionId":"FF-Session-1681087839601",
                     "id":"SofiaQuery",
                     "searchtype":"SINGLE",
                     "proposalSection":"closed",
                     "observationSection":"closed",
                     "instrument":"FORCAST",
                     "configuration":"",
                     "bandpass_name":"",
                     "instrumentSection":"open",
                     "processing":"LEVEL_4,LEVEL_3",
                     "obstype":"",
                     "dataProductSection":"open",
                     "UserTargetWorldPt":"290.9583333333333;14.1;EQ_J2000;w51;simbad",
                     "radius":"2",
                     "camera":"SW,LW",
                     "META_INFO": {"title":"FORCAST",
                                   "tbl_id":"FORCAST",
                                   "AnalyzerId":"analyze-sofia",
                                   "AnalyzerColumns":"product_type, instrument, processing_level",
                                   "DEFAULT_COLOR":"pink","DataSource":"file_url","ImagePreview":"preview_url","selectInfo":"false--0"},
                     "tbl_id":"FORCAST","spectral_element":"","tab":"instrument"}
                   })
```
but the above doesn't work; the response is an error:
```json
[{'success': 'false',
  'error': 'Unable to get query processor for ID_NOT_DEFINED: Cannot invoke "java.lang.Class.newInstance()" because the return value of "java.util.Map.get(Object)" is null'}]
```
that I suspect is caused by the Session ID parameter `"ffSessionId":"FF-Session-1681087839601",`, which is not directly accessible through the web API afaict.

**Comment by keflavich** [comment]
I don't see SOFIA anything listed in the VO "available catalogs" list (https://irsa.ipac.caltech.edu/docs/vo_scs.html#available_catalogs), so it seems a generic SIA/TAP approach won't work.

**Comment by keflavich** [comment]
I've reconstructed more of the interface, but I'm still stuck.  A websocket connection is needed to make this work, but even with the websocket data included, I'm still hitting `[{'success': 'false',
   'error': 'Unable to get query processor for ID_NOT_DEFINED: Cannot invoke "java.lang.Class.newInstance()" because the return value of "java.util.Map.get(Object)" is null'}],`
