### ISSUE TITLE
Race condition in tests with query with multiple test runners

### ISSUE THREAD

**Issue by mfisherlevine** [astropy/astroquery#2273]
With several processes running (external) tests, `if not os.path.exists(self.cache_location):` can return `True` while the dir is being made, leading to a crash on the following line. Instead, use `os.makedirs(self.cache_location, exist_ok=True)`

**Comment by bsipocz** [comment]
@mfisherlevine  - PR is welcome to make the changes.

**Comment by mfisherlevine** [comment]
First timer, so just looking at how to make it 🙂 Coding is done, just looking for if there are naming conventions on branches, or if I need to fork or can contribute directly...

**Comment by mfisherlevine** [comment]
Ah, looks like I accidentally created a new issue while trying to do it the automated way with GitHub, sorry about that! Hope that ends up being OK though 🤞

**Comment by bsipocz** [comment]
We follow the fork --> PR model. The suggestion is to make a feature branch on your fork rather than using it's 'main', but beyond that the are no naming conventions.

Here is a very detailed workflow docs, you don't need to follow it to the letter, mainly use it as a guideline (some things work here differently, e.g. changelog entries. So if you have any questions feel free to ask rather than spending awful lot of time trying to figure it out on your own and learn that we do that particular thing differently): https://docs.astropy.org/en/latest/development/workflow/development_workflow.html

And here is an example for fixing a bug, I think probably the most useful guide we have: https://docs.astropy.org/en/latest/development/workflow/git_edit_workflow_examples.html#astropy-fix-example

**Comment by bsipocz** [comment]
> Ah, looks like I accidentally created a new issue while trying to do it the automated way with GitHub, sorry about that! Hope that ends up being OK though

This is all OK. That's your pull request and cross references just work. We find it usually more useful if there is a description and title that is not just referring to an issue (so we don't have to click through to see what's about but see straight away from the notification). Anyway, all of that metadata can be edited on the PR.

Also, using the github web interface works in simpler cases like this when there is a one-liner change, with likely no need for follow-up changes after review. For the longer run setting up a fork and doing changes locally would likely be more convenient.
