### ISSUE TITLE
jplhorizons, inaccuracy in returned vectors

### ISSUE THREAD

**Issue by r-zachary-murray** [astropy/astroquery#2293]
Using astroquery to get the positions of certain solar system objects sometimes returns inaccurate state vectors.  Consider the following short script:

```
import numpy as np
import astroquery
from astroquery.jplhorizons import Horizons
import requests

#use Horizons to get the coordinates of an asteroid 
req = astroquery.jplhorizons.Horizons(id="A847 UA", location="@0",epochs=2456920.156778431) 
state_vec1 = req.vectors(refplane='earth')['x','y','z'].to_pandas().values[0] #get the carteisan state
print(state_vec1[0],state_vec1[1],state_vec1[2])


#Check the result with requests module
requrl = str(req.uri) #this returns the queried URL as a string
output = requests.get(requrl).text #lets fetch the information 
tjdb,cal,x,y,z,vx,vy,vz,lt,rg,rr = output.split('$$SOE')[1].split('$$EOE')[0].strip().split(',')[:-1] #now we'll read the information ourselves
state_vec2 = [float(x),float(y),float(z)]
print(state_vec2[0],state_vec2[1],state_vec2[2])

#The two results are different!
print(state_vec1 - state_vec2)

```
When I run this code, I get the following output:

```
-0.3145677984245455 1.830926422743566 0.7475257363993806
-0.3145677994370123 1.830926421091465 0.7475257354865833
[1.01246678e-09 1.65210090e-09 9.12797282e-10]
```

The result given by *vectors*  only agrees with the values written in *uri* to 9 decimal places.  The values given in the *uri* agree with queries from JPL's web application.  The magnitude of the disagreement seems to depend on the object queried: e.g. It occurs in the 7th digit for the Gaia Spacecraft (id = -139479) 

My system is Ubuntu 18.04.5
Python Version: 3.6.9
Numpy Version: 1.19.5
Astroquery Version: 0.4.5

**Comment by bsipocz** [comment]
cc @mkelley

**Comment by mkelley** [comment]
Hmmm, I run the code and the result is:
```
-0.3145677994370123 1.830926421091465 0.7475257354865833
-0.3145677994370123 1.830926421091465 0.7475257354865833
[0. 0. 0.]
```
Ubuntu 21.04
Python 3.8.11
numpy 1.18.5
astroquery 0.4.5

And since you used `to_pandas` I'll add:
pandas 1.1.4

By the way, you can get the actual text that astroquery is parsing with `req.raw_response`.  That way you can eliminate any changes between the astroquery call and the requests call.  But that makes me think, could this be an cache issue?  The data you are checking is from 2014.  Might it be that you queried this object some time in the past and now the ephemeris at Horizons has changed?  Try again with `cache=False` in the vectors call (keeping the separate requests call for now):
```
state_vec1 = req.vectors(refplane='earth', cache=False)
```

If that isn't it, I can certainly code up a precision test (if there isn't one already) and run that through astroquery's testing suite, which will check different versions of Python and dependencies.

**Comment by r-zachary-murray** [comment]
Thanks for the response, disabling the caching solves my problem. I'll close the issue.
