### ISSUE TITLE
getting and sorting 'rot' values from simbad/measurements

### ISSUE THREAD

**Issue by fpaletou** [astropy/astroquery#243]
i'm looking for a way to get and sort 'rot' values (eg, the most recent one) from simbad/measurements (using astroquery.simbad ressources) - thanks

**Comment by ManonMarchand** [comment]
To answer the original question, for now you can use pyvo:

```python
import pyvo
simbadtap = pyvo.dal.TAPService("https://simbad.cds.unistra.fr/simbad/sim-tap/")
query = """
SELECT RA,
       DEC,
       main_id AS "Main identifier",
       nbref AS "NbReferences",
       bibcode AS "Rotation Measurements Bibcodes"
FROM basic JOIN ident ON ident.oidref = oid
JOIN mesrot on mesrot.oidref = oid
WHERE id = 'Sirius';
"""
```

That gets you the list of the bibcodes that contain a rotation measurement for Sirius. 

```
<Table length=6>
        ra                dec         Main identifier NbReferences Rotation Measurements Bibcodes
       deg                deg                                                                    
     float64            float64            object        int32                 object            
------------------ ------------------ --------------- ------------ ------------------------------
101.28715533333335 -16.71611586111111       * alf CMa         1507            2016A&A...589A..83G
101.28715533333335 -16.71611586111111       * alf CMa         1507            2002A&A...393..897R
101.28715533333335 -16.71611586111111       * alf CMa         1507            1995ApJS...99..135A
101.28715533333335 -16.71611586111111       * alf CMa         1507            1970CoKwa.189....0U
101.28715533333335 -16.71611586111111       * alf CMa         1507            1970CoAsi.239....1B
101.28715533333335 -16.71611586111111       * alf CMa         1507            2011A&A...531A.143D

```

To construct your own queries, you can use the [Simbad database schema](https://simbad.cds.unistra.fr/simbad/tap/tapsearch.html) or the search tree on [taphandle](http://saada.unistra.fr/taphandle/?url=http%3A//simbad.u-strasbg.fr/simbad/sim-tap/). Here we joined `basic` to `ident` to be able to search Sirius by its name and then joined this to `mesrot` to get information about rotation measurements. 

I'll close the issue if no one raises a hand against because the second part about getting a TAP query for Simbad should be handled when dealing with #1468
