### ISSUE TITLE
Cannot connect to SVO Filter Profile Service

### ISSUE THREAD

**Issue by vrodgom** [astropy/astroquery#2508]
There seem to be connectivity issues with the SVO Filter Profile Service (FPS). The following code (from the [tutorial](https://astroquery.readthedocs.io/en/latest/svo_fps/svo_fps.html))

```
from astroquery.svo_fps import SvoFps
index = SvoFps.get_filter_index()
```

gives the following error:

```
ReadTimeout: HTTPConnectionPool(host='svo2.cab.inta-csic.es', port=80): Read timed out. (read timeout=60)
```

Since I can access the SVO FPS directly via my web browser, I assume the problem must lie somewhere in the interface between Astroquery and the SVO FPS.

**Comment by keflavich** [comment]
I can reproduce this, but I was also successfully querying SVO-FPS earlier this weekend, so I hope and suspect it is a temporary problem.  If it persists through tomorrow , we might want to test using different user-agents.

**Comment by eerovaher** [comment]
What is actually happening is that the default `get_filter_index()` query is too large to finish within the 60 second default timeout limit because the wavelength range is set to be as large as 64-bit floats allow. Queries with small wavelength ranges succeed just fine, so there is no reason to suspect connection issues.

The default wavelength limits are obviously not working, so I have opened a pull request that makes specifying them by the user mandatory.
