### ISSUE TITLE
JWST query returns no data acquired after Feb 28 

### ISSUE THREAD

**Issue by bhilbert4** [astropy/astroquery#2680]
Hello,

A couple users of our [jwst_mast_query](https://github.com/spacetelescope/jwst_mast_query) tool have run into an odd issue, where query results for JWST data do not include any data taken after February 28th. I was able to replicate the problem with the minimal example below. In this case, Observation 004 of JWST program 2311 completed on March 5 (MJD 60008.9), but the only files listed in the query results are those from Observation 005, which completed on Feb 28 (MJD 60003).  Using the MAST portal, I've confirmed that the Observation 004 files are present in the archive. Could it be some issue with February having only 28 days?

thanks,
Bryan

```
# Search for MIRI data from program 2311 acquired between MJD 59999 and 60010
from astroquery.mast import Mast

JwstObs = Mast()
server = 'https://mast.stsci.edu'
JwstObs._portal_api_connection.MAST_REQUEST_URL = server + "/portal_jwst/Mashup/Mashup.asmx/invoke"
JwstObs._portal_api_connection.MAST_DOWNLOAD_URL = server + "/jwst/api/v0.1/download/file"
JwstObs._portal_api_connection.COLUMNS_CONFIG_URL = server + "/portal_jwst/Mashup/Mashup.asmx/columnsconfig"
JwstObs._portal_api_connection.MAST_BUNDLE_URL = server + "/jwst/api/v0.1/download/bundle"

instrument = 'miri'
service = 'Mast.Caom.Filtered'

colnames = ['proposal_id','dataURL','obsid','obs_id','t_min','t_exptime']
columns = ','.join(colnames)

params = {"columns":columns,
                  "filters":[
                           {"paramName":"obs_collection","values":["JWST"]},
                           {"paramName":"instrument_name","values":[instrument]},
                           {"paramName":"t_min",
                           "values":[{"min":59999.,"max":60010.}]},
                  ]}

params["filters"].append({"paramName":"proposal_id","values":['02311']})

out = JwstObs.service_request(service, params).to_pandas()

In [13]: out
Out[13]: 
  proposal_id                                            dataURL      obsid                                obs_id         t_min  t_exptime
0        2311  mast:JWST/product/jw02311-o005_t005_miri_f560w...  118051911   jw02311-o005_t005_miri_f560w-sub256  60003.544127     64.696
1        2311  mast:JWST/product/jw02311-o005_t005_miri_f1000...  118051912  jw02311-o005_t005_miri_f1000w-sub256  60003.555917     64.696
2        2311  mast:JWST/product/jw02311-o005_t005_miri_f1800...  118051913  jw02311-o005_t005_miri_f1800w-sub256  60003.575972    609.824
3        2311  mast:JWST/product/jw02311-o005_t005_miri_f770w...  118051914   jw02311-o005_t005_miri_f770w-sub256  60003.549708     64.696
4        2311  mast:JWST/product/jw02311-o005_t005_miri_f2100...  118051915  jw02311-o005_t005_miri_f2100w-sub256  60003.587776   1208.864
5        2311  mast:JWST/product/jw02311-o005_t005_miri_f1500...  118051916  jw02311-o005_t005_miri_f1500w-sub256  60003.567604    310.304
6        2311  mast:JWST/product/jw02311-o005_t005_miri_f1280...  118051917  jw02311-o005_t005_miri_f1280w-sub256  60003.561394    124.600
```

**Comment by bsipocz** [comment]
cc @jaymedina

**Comment by jaymedina** [comment]
Hi @bhilbert4 - It looks like the 004 observations are under the instrument name `MIRI/IMAGE` instead of just `MIRI`. I added `MIRI/IMAGE` to the instrument parameter in the query and got the 004 observations:

```
# Search for MIRI data from program 2311 acquired between MJD 59999 and 60010
from astroquery.mast import Mast

JwstObs = Mast()
server = 'https://mast.stsci.edu'
JwstObs._portal_api_connection.MAST_REQUEST_URL = server + "/portal_jwst/Mashup/Mashup.asmx/invoke"
JwstObs._portal_api_connection.MAST_DOWNLOAD_URL = server + "/jwst/api/v0.1/download/file"
JwstObs._portal_api_connection.COLUMNS_CONFIG_URL = server + "/portal_jwst/Mashup/Mashup.asmx/columnsconfig"
JwstObs._portal_api_connection.MAST_BUNDLE_URL = server + "/jwst/api/v0.1/download/bundle"

instrument = 'MIRI/IMAGE'
service = 'Mast.Caom.Filtered'

colnames = ['proposal_id','dataURL','obsid','obs_id','t_min','t_exptime']
columns = ','.join(colnames)

params = {"columns":columns,
          "filters":[
                   {"paramName":"obs_collection","values":["JWST"]},
                   {"paramName":"instrument_name","values":['MIRI', 'MIRI/IMAGE']},
                   #{"paramName": "obs_id", "values":["jw02311-o005_t005_miri_f560w-sub256"]},
                   {"paramName":"t_min",
                   "values":[{"min":59999.,"max":60011.}]},
          ]}

params["filters"].append({"paramName":"proposal_id","values":['02311']})

out = JwstObs.service_request(service, params).to_pandas()
out
```


  | proposal_id | dataURL | obsid | obs_id | t_min | t_exptime
-- | -- | -- | -- | -- | -- | --
2311 | mast:JWST/product/jw02311-o005_t005_miri_f560w... | 118051911 | jw02311-o005_t005_miri_f560w-sub256 | 60003.544127 | 64.696
2311 | mast:JWST/product/jw02311-o005_t005_miri_f1000... | 118051912 | jw02311-o005_t005_miri_f1000w-sub256 | 60003.555917 | 64.696
2311 | mast:JWST/product/jw02311-o005_t005_miri_f1800... | 118051913 | jw02311-o005_t005_miri_f1800w-sub256 | 60003.575972 | 609.824
2311 | mast:JWST/product/jw02311-o005_t005_miri_f770w... | 118051914 | jw02311-o005_t005_miri_f770w-sub256 | 60003.549708 | 64.696
2311 | mast:JWST/product/jw02311-o005_t005_miri_f2100... | 118051915 | jw02311-o005_t005_miri_f2100w-sub256 | 60003.587776 | 1208.864
2311 | mast:JWST/product/jw02311-o005_t005_miri_f1500... | 118051916 | jw02311-o005_t005_miri_f1500w-sub256 | 60003.567604 | 310.304
2311 | mast:JWST/product/jw02311-o005_t005_miri_f1280... | 118051917 | jw02311-o005_t005_miri_f1280w-sub256 | 60003.561394 | 124.600
2311 | mast:JWST/product/jw02311-o004_t004_miri_f1280... | 118308091 | jw02311-o004_t004_miri_f1280w-sub256 | 60008.892183 | 124.600
2311 | mast:JWST/product/jw02311-o004_t004_miri_f770w... | 118308092 | jw02311-o004_t004_miri_f770w-sub256 | 60008.880319 | 64.696
2311 | mast:JWST/product/jw02311-o004_t004_miri_f560w... | 118308093 | jw02311-o004_t004_miri_f560w-sub256 | 60008.874724 | 64.696
2311 | mast:JWST/product/jw02311-o004_t004_miri_f1500... | 118308094 | jw02311-o004_t004_miri_f1500w-sub256 | 60008.898381 | 310.304
2311 | mast:JWST/product/jw02311-o004_t004_miri_f2100... | 118308095 | jw02311-o004_t004_miri_f2100w-sub256 | 60008.918471 | 1208.864
2311 | mast:JWST/product/jw02311-o004_t004_miri_f1800... | 118308096 | jw02311-o004_t004_miri_f1800w-sub256 | 60008.906691 | 609.824
2311 | mast:JWST/product/jw02311-o004_t004_miri_f1000... | 118308097 | jw02311-o004_t004_miri_f1000w-sub256 | 60008.886400 | 64.696

```

**Comment by bhilbert4** [comment]
Thanks @jaymedina! Do you know if this difference is intentional? Looking in the APT file for 2311, observations 4 and 5 are identical other than target. I don't understand why the instrument value would be different between them. I'm mainly wondering if I'll have to edit our tool to query MAST for <instrument>/<mode> in addition to just <instrument>.

**Comment by bsipocz** [comment]
As I see there is nothing to do in astroquery about this as it's purely an upstream question/issue. I'm closing this now, but feel free to continue the discussion here.

**Comment by jaymedina** [comment]
No worries @bhilbert4 . I'm not sure why that parameter is different, since both observations contain image products, but I've posted a question on the MAST channel on slack. Once I get an answer from the database managers I'll update this thread.

**Comment by jaymedina** [comment]
Response from the database managers: 

> I think this might be mixed processing states- the newest JWST install is supposed to have MIRI/IMAGE and so as data get reprocessed they will be converted over. This was due to user confusion with planned observations which have richer instrument names

> Just checked on the DB and indeed, MIRI/IMAGE is used after 2/28 when the new version got installed.

**Comment by bhilbert4** [comment]
Thanks! I've been following the slack discussion as well.
