### ISSUE TITLE
BUG : DALQueryError occured querying calibrators

### ISSUE THREAD

**Issue by peterlai500** [astropy/astroquery#2835]
Hi, 

I'm using astroquery (0.4.7.dev8738). The `DALFormatError` always happens when I attempt to continuously query calibrators in a list. 
However when I substitute maxrec to 100 and 10, the error message change to `DALQueryError`.

I also tried to change the archive server to East Asia and Europe. The error still exists.

Thank you for your help.

The query code and the targets I want to query are here.
<pre><code>targets = ['J0423-0120', 'J2253+1608', 'J0522-3627', 'J1924-2914', 'J1308+1140', 'J0501-0159]
for target in targets:
    result = Alma.query(
                        payload=dict(source_name_alma=target, polarisation_type="Dual"),
                        science=False,
                        maxrec=1000
                       )
    print(f'Querying {target}, data length : {len(result)}')
</code></pre>

The Error messages are here.
>DALFormatError: ValueError: 48742:421: XML or text declaration not at start of entity

>DALQueryError: ORA-01489: result of string concatenation is too long
 ORA-01489: result of string concatenation is too long

**Comment by bsipocz** [comment]
I wonder whether this is the same as https://github.com/astropy/astroquery/issues/2649? 

cc @andamian

**Comment by andamian** [comment]
@peterlai500 - thanks for reporting.
A fix for the `DALQueryError` error has been submitted to ALMA and should be available with their next release. 

I'm not sure what the `DALFormatError` is. I've tried to reproduce it without specifying a radius but it only happened once (the rest it was the `DALQueryError`. I suspect that the return result is malformatted somehow. Let me know if you are able to consistently reproduce it so that I can follow up. Thanks

**Comment by andamian** [comment]
This has been fixed upstream.
