### ISSUE TITLE
AttributeError: 'VizierClass' object has no attribute 'get_catalog_metadata'

### ISSUE THREAD

**Issue by Roseane19** [astropy/astroquery#2962]
Hello everybody!

I am trying to get information such as title, author, year, doi, etc. from a catalog.
For that, I've used the function get_catalog_metadata(), but I've got this following error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[11], line 2
      1 from astroquery.vizier import Vizier
----> 2 Vizier(catalog="VII/74A").get_catalog_metadata()

AttributeError: 'VizierClass' object has no attribute 'get_catalog_metadata'

It's important for me to do this automatically because, I have a long list of catalogs and I wish to make a loop to construct a table with these additional information.

I really appreciate if anyone could help me.

**Comment by ManonMarchand** [comment]
Hello, 

This was added in the last version of astroquery. Could you try: 

```
python -m pip install -U --pre astroquery
```

And tell us if the issue is still there?

**Comment by ManonMarchand** [comment]
PS: if your list is super long, doing this in a loop might not work.

You can either
-  add pauses in your loops so that you don't get banned for sending too much requests
-  or do a custom ADQL query like so:

```python
from pyvo.dal.tap import TAPService
from astropy.table import Table

# set up a link to VizieR
tapvizier = TAPService("https://tapvizier.cds.unistra.fr/TAPVizieR/tap")

# the list of catalogs that you want to inspect should be the columns of an astropy Table object
# this table will be uploaded to VizieR to use in a query
list_of_catalogs = Table([["VII/74A", "I/355"]], names=["name"])

# an ADQL query
query = "SELECT name, title, bibcode, authors  FROM TAP_UPLOAD.catalogs JOIN METAcat USING(name)"

# the actual connection to VizieR
tapvizier.search(query, uploads={"catalogs": list_of_catalogs}).to_table()

```

```
<Table length=2>
  name                           title                                bibcode            authors      
 object                          object                                object             object      
------- ------------------------------------------------------- ------------------- ------------------
  I/355 Gaia DR3 Part 1. Main source (Gaia Collaboration, 2022) 2022yCat.1355....0G Gaia collaboration
VII/74A                   Atlas of Peculiar Galaxies (Arp 1966) 1966ApJS...14....1A           Arp H.C.
```

This second solution is way more powerful.

Where the structure of the metadata tables in vizier can be found here : http://tapvizier.u-strasbg.fr/adql/img/vizdb.png 
In this example we only look at the METAcat table, but you might want to look at way more information!

To learn more about ADQL (the content of the string in the `query` variable), you can have a look here http://tapvizier.cds.unistra.fr/adql/about.html

**Comment by Roseane19** [comment]
Hello @ManonMarchand , this second solution is truly more powerful. 
Thank you very much for your help!!!
