### ISSUE TITLE
astroquery NoResultWarning with Cycle 1 and Cycle 2 data

### ISSUE THREAD

**Issue by GalagaBits** [astropy/astroquery#2972]
When attempting to use astroquery on the following JWST Cycle 1 and Cycle 2 data, the error `WARNING: NoResultsWarning: Query returned no results. [astroquery.mast.discovery_portal]` appears:

```
# Cycle 1
pid=2512
obs_num = 1

if obs_num != 'None':
    matched_obs = Observations.query_criteria(
        obs_collection = 'JWST',
        proposal_id=str(pid),
    )
    
    data_products = [Observations.get_product_list(obs) for obs in matched_obs]
```

```
# Cycle 2
pid=3730
obs_num = 1
visit = 1
if obs_num != 'None' and visit != 'None':
    matched_obs = Observations.query_criteria(
        obs_collection = 'JWST',
        proposal_id=str(pid),
    )
    
    data_products = [Observations.get_product_list(obs) for obs in matched_obs]
```

However, all data products are seemingly downloaded and ready to use. Is this an expected issue?

**Comment by bsipocz** [comment]
cc @astrojimig

**Comment by GalagaBits** [comment]
@bsipocz, how do I cc @astrojimig? Is tagging them here enough?

**Comment by keflavich** [comment]
@GalagaBits Posting "@<someone's name>" sends them a notification.  That wasn't an instruction to you, that was Brigitta cc'ing astrojimig

**Comment by astrojimig** [comment]
Yes, apologies for the slow response! I will look into this tomorrow.

**Comment by GalagaBits** [comment]
@keflavich Oh okay, I thought it might have been an instruction

**Comment by GalagaBits** [comment]
@astrojimig Okay! Thank you!

**Comment by astrojimig** [comment]
The warning here is correct. In your example, the first observation has no associated data products.

```
>>> from astroquery.mast import Observations
>>> pid = 2512
>>> matched_obs = Observations.query_criteria(obs_collection = 'JWST', proposal_id=str(pid))

# Query returns 47 observations
>>> len(matched_obs)
47

# First Observation in list returns no products, prints warning
>>> data_products = Observations.get_product_list(matched_obs[0])
WARNING: NoResultsWarning: Query returned no results. [astroquery.mast.discovery_portal]
>>> len(data_products)
0

# Second Observation in list returns 662 products, no warning
>>> data_products = Observations.get_product_list(matched_obs[1])
>>> len(data_products)
662
```

Because you loop through all observations in that program ID, you are still able to download files associated with the other observations, but the warning is correct that the first observation does not return any products.

As for why that observation returns no results, the observation table can give us some hints:

```
>>> matched_obs[0]['proposal_id','obs_collection','obs_id', 'calib_level', 't_min', 't_obs_release']
<Row index=0>
proposal_id obs_collection               obs_id              calib_level  t_min  t_obs_release
----------- -------------- --------------------------------- ----------- ------- -------------
       2512           JWST jw02512021001_xx102_00001_nirspec          -1     nan           nan

```

The `calib_level = -1 `and` t-min = nan` tells me that while this observation was planned, it has not been observed as of yet.


[Performing the same search in the MAST Web Portal confirms this](https://mast.stsci.edu/portal/Mashup/Clients/Mast/Portal.html?searchQuery=%7B%22service%22%3A%22CAOMFILTERED%22%2C%22inputText%22%3A%5B%7B%22paramName%22%3A%22project%22%2C%22niceName%22%3A%22project%22%2C%22values%22%3A%5B%22JWST%22%5D%2C%22valString%22%3A%22JWST%22%2C%22isDate%22%3Afalse%2C%22separator%22%3A%22%3B%22%2C%22facetType%22%3A%22discrete%22%2C%22displayString%22%3A%22JWST%22%7D%2C%7B%22paramName%22%3A%22proposal_id%22%2C%22niceName%22%3A%22proposal_id%22%2C%22values%22%3A%5B%5D%2C%22valString%22%3A%222512%22%2C%22isDate%22%3Afalse%2C%22freeText%22%3A%222512%22%2C%22displayString%22%3A%222512%22%7D%5D%2C%22position%22%3A%22undefined%2C%20undefined%2C%20undefined%22%2C%22paramsService%22%3A%22Mast.Caom.Filtered%22%2C%22title%22%3A%22MAST%3A%20%20Advanced%20Search%201%22%2C%22tooltip%22%3A%22JWST%3B%202512%3B%20%22%2C%22columns%22%3A%22*%22%2C%22columnsConfig%22%3A%22Mast.Caom.Cone%22%7D), with the first row saying: "Data for this observation are from an accepted proposal that has not executed yet." The same is true for several observations in your Cycle 3 example.

I hope that helps! Let me know if you have any follow-up questions.
