### ISSUE TITLE
solarsystem.imcce: Cannot choose the dynamical model for the motion of satellites?

### ISSUE THREAD

**Issue by qing-xue** [astropy/astroquery#2992]
[astroquery.imcce](https://astroquery.readthedocs.io/en/latest/imcce/imcce.html#module-astroquery.imcce)/astroquery.solarsystem.imcce

Although users can choose the planetary theory such as 'INPOP', they cannot choose the dynamical model for the motion of satellites such as 'ura111'. Can this issue be solved in the future? Or are there other solutions?

**Comment by bsipocz** [comment]
cc @mkelley

**Comment by mkelley** [comment]
@qing-xue Can you clarify the issue?  I'm not very familiar with Mirade's ephemeris service and I don't see anything in the API documentation that correlates with the selection of dynamical models for satellites: https://ssp.imcce.fr/webservices/miriade//api/ephemcc/#webservice

If you see a way to get what you need through this API, but astroquery does not support it, please explain further so that we can fix that.

**Comment by qing-xue** [comment]
Thank you. I find that there is another website of IMCCE service: [http://nsdb.imcce.fr/multisat/nssreq7he.htm](http://nsdb.imcce.fr/multisat/nssreq7he.htm), in which the user can choose the theory for satellites as well as the planetary emphemerides. I'm not sure whether these two website are the same. Do you have any plans to support this website's API?

**Comment by mkelley** [comment]
I think the question has been addressed, but whether or not a new service could be added should be addressed in a separate issue.
