### ISSUE TITLE
MAST: Tesscut doc needs updating, cloud API is no-op

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#3097]
As requested by @orionlee in https://github.com/astropy/astroquery/issues/1521#issuecomment-2365429961

Public documentation should probably be updated, as `TessCut` class still have the documented 
[`enable_cloud_dataset()`](https://astroquery.readthedocs.io/en/latest/api/astroquery.mast.TesscutClass.html#astroquery.mast.TesscutClass.enable_cloud_dataset) and [`disable_cloud_dataset()`](https://astroquery.readthedocs.io/en/latest/api/astroquery.mast.TesscutClass.html#astroquery.mast.TesscutClass.disable_cloud_dataset) methods that are essentially no-ops.

**Comment by bsipocz** [comment]
cc @snbianco

**Comment by snbianco** [comment]
Looks like the issue here is that `enable_cloud_dataset` and `disable_cloud_datset` are defined on the base class of `TesscutClass`, which is `MastQueryWithLogin`. 

Some options:
1. Override the functions in `TesscutClass`, issue a deprecation warning, and add a `:private` directive to hide them from the docs.
2. Override the functions in `TesscutClass` and raise an exception.
3. Move the functions into the child classes excluding `TesscutClass`.

I'm leaning towards Option 1, but I wanted to check if there is a standard already in place for this type of thing.

**Comment by pllim** [comment]
If these are used in child classes, you could also raise `NotImplementedError` in the base class with a message that it should be defined in child classes. Ultimately, it is up to you, as I am unfamiliar with MAST API internals. Thanks!
