### ISSUE TITLE
Remove `AstropyLogger` as the logger class

### ISSUE THREAD

**Issue by snbianco** [astropy/astroquery#3120]
@pllim 

As noted in the [Astropy docs](https://docs.astropy.org/en/latest/logging.html), the `AstropyLogger` class is meant for internal usage. There's at least one issue with using this class in astroquery, which is that lazy formatting in log messages does not work correctly.  The Astropy documentation suggests that other packages should implement their own logger.

**Comment by bsipocz** [comment]
Internal is kind of interpreted as internal in the astropy ecosystem. We do use a lot of `utils` here and in other affiliated packages, and unless there is a really compelling reason I would rather see stuff being fixed up upstream than multiplicating the problems, technical debt and maintenance burden with redoing stuff downstream.

**Comment by pllim** [comment]
You have more freedom to explore more modern logging solutions and customize the behavior to your liking if you are not tied to the logger class from `astropy`.

**Comment by bsipocz** [comment]
Upstream has been fixed (but of course we can't do lazy logging util the min required astropy version reaches 6.1.5), so I'm closing this issue here. 

As we discussed it already, I see no issues with astroquery not using lazy logging, we and our users are absolutely limited by the data download and server sides, so no need to overoptimize the few logging lines we would do.
