### ISSUE TITLE
Batch coordinate query of SDSS

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#492]
At the moment the batch queries are not working properly in ``SDSS.query_region()``, and the maximum number of query-able coordinates seems to be only 21 (otherwise a ``400 Bad request`` response is returned).

 I couldn't find the reason for this small number on their web pages,  and http://skyserver.sdss.org/dr12/en/tools/crossid/crossid.aspx doesn't seem to have this limitation. It's possible that it can be avoided with directly feeding the coordinates to ``query_sqr()`` (haven't tested whether it works or not).

**Comment by eteq** [comment]
@bsipocz - I haven't had a chance to look to see if this is true for the astroquery code yet, but have encountered it my own science: could it be that the query is being sent with GET?  If you use GET instead of POST, you often hit the maximum size for a URL, but POST can be arbitrarily long.

If that's the problem I'll try to find the time to take a crack at this because I've solved it myself in science code.

**Comment by bsipocz** [comment]
@eteq - Many thanks! It indeed uses GET. I'm testing whether it brakes if it's switched to POST.

**Comment by eteq** [comment]
@bsipocz - FYI, http://skyserver.sdss.org/dr12/en/help/docs/api.aspx is a difficult-to-find but extremely valuable page for this
