### ISSUE TITLE
ReadTheDocs build broken

### ISSUE THREAD

**Issue by keflavich** [astropy/astroquery#558]
https://readthedocs.org/builds/astroquery/3024401/

`OSError: Could not find unix home directory to search for astropy config dir`

@astrofrog have you seen this on any other repos?

**Comment by astrofrog** [comment]
No, I've not seen this before, but doesn't mean it wouldn't happen now with new builds. Can check later.

**Comment by astrofrog** [comment]
In the mean time, maybe @mdboom or @embray have some ideas?

**Comment by mdboom** [comment]
I think `astroquery` is pretty unique in that it calls `get_cache_dir` during import time and therefore it's getting triggered by readthedocs.  It's yet quite clear to me why we are just seeing this now -- neither astroquery or astropy has changed in this regard recently.  Maybe readthedocs' environment recently changed to no longer have a usable `$HOME`?  (Can't find any changelog or such for readthedocs that would explain that).  That seems unlikely, since the paths in the readthedocs output hint at the existence of `/home/docs/`...

I'm always wary of trying to fix something without first understanding why it's failing, but I suppose here we could return a temp directory when the lookup of `$HOME` fails...

**Comment by keflavich** [comment]
@mdboom is it wrong to be getting the cache directory at import time?  That seems like something that would be useful for configuration-related tools.

I am also perplexed about seeing the effects suddenly.

I'm not very familiar with the helper system in general - should I be making a change in astroquery to work around this (i.e., the home lookup), or is it something that could be implemented in helpers?

**Comment by mdboom** [comment]
> @mdboom is it wrong to be getting the cache directory at import time? That seems like something that would be useful for configuration-related tools.

No, I don't think it's wrong -- it's just that astropy and many other affiliated packages don't.  I only mentioned it to explain why we've only noticed it with astroquery.

> I'm not very familiar with the helper system in general - should I be making a change in astroquery to work around this (i.e., the home lookup), or is it something that could be implemented in helpers?

I think we probably can and should work around it in astropy itself -- I'm having trouble imagining any negative consequences to returning a temporary directory if a cache directory can't be found, but it also feels like one of those things that's full of unintended consequences.

**Comment by bsipocz** [comment]
RTD is working fine for a while, so closing this issue.
