### ISSUE TITLE
Update IRSA docstring

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#681]
Docstring should be rewised for `IrsaClass`, e.g. there is no Notes section listing the available options for the `catalog` parameter.

https://github.com/astropy/astroquery/blob/master/astroquery/irsa/core.py#L191

**Comment by AyushYadav** [comment]
@bsipocz @keflavich @eteq Its a small fix for the users to know where to find the ``''catalog`` str values. Instead of adding Notes I have added a simple command to enable users to find the appropriate catalog from the IRSA archive. We can also do a seperate HTML thing but I think this will be sufficient to the variable clear.

**Comment by agarwalrounak** [comment]
@bsipocz this issue can be closed. It was solved in PR #851
