### ISSUE TITLE
Declaring a dependency on astroquery with conda

### ISSUE THREAD

**Issue by josePhoenix** [astropy/astroquery#707]
It looks like `astropy` has a conda package in the main conda package namespace, but `astroquery` does not. I'm trying to package [something](https://github.com/spacetelescope/jwst_visibility) for [astroconda](http://astroconda.readthedocs.io/en/latest/) that depends on astroquery.

Typically, for packages without conda build recipes, we have been making our own. However, astroquery seems to have a conda package that's just on a separate channel. I'm not aware of any way to depend on a specific package and channel, and I fear what would happen if we made our own astroquery recipe under the astroconda channel, so I'm wondering if there are plans to make an astroquery package available in the main conda package index.

Thanks!

cc @jhunkeler

**Comment by bsipocz** [comment]
cc @mwcraig who is the person behind the astropy conda channel

**Comment by mwcraig** [comment]
@josePhoenix -- there are a couple routes you could go. You are right that there is not, at least for now, an easy way for one channel to automatically include packages from another channel.

Some options:

+ You could build astroquery in your channel. IIRC, we build it in the astropy conda channel basically by running `conda skeleton pypi astroquery` And then `conda build astroquery` (though it has a couple of dependencies too).
+ You could copy the astroquery conda package (and its dependencies) from the astropy conda channel to your conda channel using either `anaconda copy` at the command line (I think you need to install the anaconda-client conda package to get this), or I can post a python script that does the same thing.
+ You could have users add both the astroconda channel and the astropy channel to their conda configure (not ideal because it is a little more comlicated and because there is no way to specify which package gets installed if the same package is in both channels).

I'm planning to work a bit at this end of this week on automating some channel copying stuff for the astropy channel and the open astronomy channel.

You should also be aware of the conda-free channel (see conda-forge.github.io for more). In the long run that may become the de facto default channel.

**Comment by bsipocz** [comment]
@josePhoenix - Does any of the options in @mwcraig's answer work for you? If yes, could you please close this issue?

**Comment by josePhoenix** [comment]
Unfortunately, I had to reimplement the small part of AstroQuery I was using because Astropy does not package well with PyInstaller (see extensive discussion at https://github.com/astropy/astropy/pull/960). I will go ahead and close this issue.
