### ISSUE TITLE
Provide catalogue number for a target

### ISSUE THREAD

**Issue by ceyzeriat** [astropy/astroquery#733]
I had a look at the guts of the code, but can't really find what's the best place to put this, so I open an issue/improvement instead.

When one queries a target through a name, e.g. "vega", it is often useful to access its catalog numbers to cross reference it with other sources, e.g. for vega HR 7001, HIP 91262, HIC 91262, HD 172167 for the most famous ones for stars. Ideally, it could work for any catalog (messier, WLY, NGC, 2MASS, ...), and even return the "constellation name of the star", e.g. "Alpha Lyrae" for vega.

I know Simbad keeps track of most catalog numbers/names for a target, which are querried with `query_objectids`. A way to implement this would be to create a dictionary of `{'catalog_short_name': catalogue_number_or_string}` from the result of the `query_objectids` method.

What do you think?

**Comment by keflavich** [comment]
I like the idea, but don't immediately know how to implement it.  Would this be a relatively small list, ~1000 named objects, that we'd want to create and cache locally?

**Comment by ceyzeriat** [comment]
VizieR says there are 14000+ catalogs http://vizier.u-strasbg.fr/viz-bin/VizieR-2

Not sure we should record catalog IDs, because anyway, it seems that the only way to get the catalog numbers is to parse strings.

Note also that a dummy real-expression is able to extract correctly the different catalogs ID/numbers for the case of vega:
```
from astroquery.simbad import Simbad
import re
for i in Simbad.query_objectids('vega')['ID']:
  print("%-35s : %10s : %s"%((i,)+re.match('([^ \-\+]+) *(.+)$', i).groups()[0:2]))
```
to be compared to http://simbad.u-strasbg.fr/simbad/sim-basic?Ident=vega&submit=SIMBAD+search

The IDs just have to be cleaned a bit to become dict-keys, and the "numbers" converted to int when possible.. and that's it!

**Comment by aoberto** [comment]
Hi,

I just want to warn you that in catalogues some entries are not really distinct object.
And then in Simbad, you will get 2 (and some times more) that one number ID per catalogue.
For example : http://simbad.u-strasbg.fr/simbad/sim-id?Ident=HD+1237
has 2 numbers for WDS, HD etc.

Also, you should be restricted to a list of given catalogues because there is not always a simple correlation between an acronym+number in the identifier in Simbad and the name in a catalogue.
Some are quite easy, and you can see them in the "External archives" section in the web page of Simbad.

**Comment by ceyzeriat** [comment]
Hm, true, thanks. Indeed multiple stars are weirdly referenced, and that's probably just the visible part of the iceberg.
Well, either we get a database of catalogue-IDs of the most famous catalogues, together with a method that is able to extract the "number" of the target in the catalogue from the list of string-identifiers no matter the weirdness of it.
Or we set-up some parser on the "External archives" part, that seems to be "cleaner" on catalogues naming/duplicates.

**Comment by bsipocz** [comment]
For reproducibility we should always return whatever the webservices provide, and shouldn't try to be more cleaver than they are. If there are multiple name returned on simbad from a catalogue, then we should return a list of such names.

If it's a crossmatch with Vizier or any other extrernal services, then it should be a classmethod of the Vizier etc rather than the Simbad module.

In general, if there are problems with the given service, we should aim to report those problems upstream rather than trying to patch to get the "right answer" here.

**Comment by bsipocz** [comment]
Given the last comment, this is more of a suggestion for upstream or for concrete user workflows. We don't plan to build in anything along the proposed lines to override the default responses.
