### ISSUE TITLE
Travis CI with remote data not real?

### ISSUE THREAD

**Issue by pllim** [astropy/astroquery#862]
There are two remote data tests (`-R` and `--remote-data`) in Travis CI but they are not reporting any test results. For example, see https://travis-ci.org/astropy/astroquery/jobs/212351545 . Am I missing something here?

**Comment by bsipocz** [comment]
Those are only running on push and cron commits, see ``EVENT_TYPE`` in ``.travis.yml`` (long story short we don't want to overwhelm the remote services with out testing). 
Also the reason is to have both ``-R`` and ``--remote-data`` is to provide testing the astropy testing module. I'll try to dig up some issue numbers for reference later.

**Comment by pllim** [comment]
So, am I allowed to add a remote test on Travis but only for Cone Search and have it be allowed to fail? It is currently that way in Astropy and I like that feature, at least for Cone Search.

**Comment by bsipocz** [comment]
Hmm, not sure what you mean. I would suggest to add as many remote tests as you need, but we really don't need to run them for every commit in every PR. Going by the current default, they will run for each merge commit, and once a week from cron. As you see we let those tests to fail in order to receive e-mail notifications (alma is a moving target, and there are quite many server outages, too.)

https://travis-ci.org/astropy/astroquery/builds

**Comment by pllim** [comment]
Ah, okay. I already have remote test, and I am glad they are actually run once in a while via cron (I am still not very familiar with the cron feature on Travis). It is too bad it times out like that (from the last relevant build that I saw). Pretty sure Cone Search would pass most of the time but it would unnecessarily complicate things to force Cone Search to run first though. I think you answered all my questions. Thank you! :+1:

**Comment by bsipocz** [comment]
Yeap, sometimes they time out, usually with some of the alma stuff. The "good" thing in astroquery is that we don't (as we can't) promise stability, thus occasional timeouts and server issues are part of the business. I'm sure in this environment  conesearch won't be the most flaky module :)

**Comment by pllim** [comment]
> conesearch won't be the most flaky module

I'll have to get used to that... :sunglasses:
