### ISSUE TITLE
RVZ_ERROR field is only giving the first digit of the radial velocity error

### ISSUE THREAD

**Issue by DouglasBoubert** [astropy/astroquery#960]
When using astroquery.simbad the RVZ_ERROR field has units of km/s but has type unicode1, so is only returning the first digit of the radial velocity error. Please can this be fixed?

**Comment by bsipocz** [comment]
Could you provide a minimal example code?

**Comment by DouglasBoubert** [comment]
See below. The true error is 4.6 km/s, but this returns the string '4'.

'from astroquery.simbad import Simbad
s = Simbad()
s.add_votable_fields('velocity')
result_table = s.query_object('GSC0403601718')
print(result_table['RVZ_RADVEL'][0],result_table['RVZ_ERROR'][0])'

**Comment by bsipocz** [comment]
The issue is that the result votable comes back without ``datatype`` set for ``RVZ_ERROR``:
http://simbad.u-strasbg.fr/simbad/sim-script?submit=submit+script&script=votable+%7Bmain_id%2Ccoordinates%2Cvelocity%7D%0D%0Avotable+open%0D%0Aquery+id++GSC0403601718++%0D%0Avotable+close

@keflavich - is there someone in CDS we usually contact, or should I just drop a line to ``cds-question``?

**Comment by keflavich** [comment]
I just contact the normal helpdesk. It's usually the same person helping, but they respond quickly to tickets.

**Comment by aoberto** [comment]
Hi,

I just added the missing fields

Anais

**Comment by bsipocz** [comment]
@aoberto - thanks you very much for the fix. I can confirm that the above snipped indeed works now as expected.

@DouglasBoubert - make sure you clear the relevant cache (usually located ``~/.astropy/cache/astroquery``), if it's around you may still see the previous result.

**Comment by DouglasBoubert** [comment]
@bsipocz - I can also confirm that it works as expected. Thank you for the quick fix!
